#!/bin/bash
#
# This script generates a matrix sentence corpus
#
# Copyright (C) 2014-2016 Marc René Schädler

# Get the directory this script is stored in and its name
DIR=$(cd "$( dirname "$0" )" && pwd)
SCN=$(basename "$0")

# Load configuration file
CGF="${DIR}/${SCN}.cfg"
[ -f "${CGF}" ] && source "${CGF}"

# Load additional scripts from sub-script directory
SSD="${DIR}/${SCN}.d"
[ -d "${SSD}" ] && PATH="${PATH}:${SSD}"

# Working directory is the current directory
WKD="${PWD}"

# Corpus source directory
CSD="${WKD}/source"

# Corpus directory
COD="${WKD}/corpus"

# Check if generation config file exists
if [ -z "${TRAIN_SAMPELS}" ]; then
  echo "train samples not defined"
  exit 1
elif [ -z "${TEST_SAMPELS}" ]; then
  echo "test samples not defined"
  exit 1
elif [ -z "${SNRS}" ]; then
  echo "SNRs not defined"
  exit 1
elif [ -z "${SIL}" ]; then
  echo "Start/end silence not defined"
  exit 1
elif [ -z "${TRAIN_SEED}" ]; then
  echo "Train seed not defined"
  exit 1
elif [ -z "${TEST_SEED}" ]; then
  echo "Test seed not defined"
  exit 1
fi

# Check that speech and noise data exists
NUM_SPEECH_FILES=$(find "${CSD}/speech" -type f -iname '*.wav' | wc -l)
NUM_NOISE_FILES=$(find "${CSD}/noise" -type f -iname '*.wav' | wc -l)
if [ $NUM_SPEECH_FILES -lt 1 ]; then
  echo "no speech files found in '${CSD}/speech'"
  exit 1
fi
if [ $NUM_NOISE_FILES -lt 1 ]; then
  echo "no noise files found in '${CSD}/noise'"
  exit 1
fi

# Clear target directory
[ -d "${COD}" ] && rm -r "${COD}"
mkdir -p "${COD}"

# Generate training data
mkdir -p "${COD}/train"
echo "mixsnr('${CSD}/speech', '${CSD}/noise', '${COD}/train', ${SNRS}, ${TRAIN_SAMPELS}, ${SIL}, ${TRAIN_SEED});" | run-matlab "mixing" || exit 1

# Generate test data
mkdir -p "${COD}/test"
echo "mixsnr('${CSD}/speech', '${CSD}/noise', '${COD}/test', ${SNRS}, ${TEST_SAMPELS}, ${SIL}, ${TEST_SEED});" | run-matlab "mixing" || exit 1

