#!/bin/bash
# Copyright (C) 2014-2016 Marc René Schädler
[ -f proto ] || exit 1
FLOOR="$1"
[ -z "${FLOOR}" ] && FLOOR=0.01
[ -d hmminit ] && rm -r hmminit
[ -e hmminit ] && exit 1
mkdir hmminit
HCompV \
  -f "${FLOOR}" \
  -C config \
  -m \
  -S features \
  -M hmminit \
  proto || exit 1
echo "~o" > hmminit/macros
cat proto | grep '<STREAMINFO>' >> hmminit/macros
cat proto | grep '<VECSIZE>' >> hmminit/macros || exit 1
echo "<USER>" >> hmminit/macros
cat hmminit/vFloors >> hmminit/macros || exit 1
cat hmminit/proto | grep "<MEAN>" -A1 | grep -v -E '^(<MEAN>|--)' | \
  tr '\n' ' ' | tr -s ' ' | sed -e 's/^ //g' -e 's/ $//g' > globalmean || exit 1
cat hmminit/proto | grep "<VARIANCE>" -A1 | grep -v -E '^(<VARIANCE>|--)' | \
  tr '\n' ' ' | tr -s ' ' | sed -e 's/^ //g' -e 's/ $//g'> globalvar || exit 1

