#!/bin/bash
#
# This script generates a stimulus corpus
#
# Copyright (C) 2014-2016 Marc René Schädler

# Get the directory this script is stored in and its name
DIR=$(cd "$( dirname "$0" )" && pwd)
SCN=$(basename "$0")

# Load configuration file
CGF="${DIR}/${SCN}.cfg"
[ -f "${CGF}" ] && source "${CGF}"

# Load additional scripts from sub-script directory
SSD="${DIR}/${SCN}.d"
[ -d "${SSD}" ] && PATH="${PATH}:${SSD}"

# Working directory is the current directory
WKD="${PWD}"

# Corpus generation scripts
CGS="${WKD}/config/corpus/matlab"

# Corpus directory
COD="${WKD}/corpus"

# Check if generation config file exists
if [ -z "${TRAIN_SAMPELS}" ]; then
  echo "train samples not defined"
  exit 1
elif [ -z "${TEST_SAMPELS}" ]; then
  echo "test samples not defined"
  exit 1
fi

# Check that matlab generation script exists
if [ ! -f "${CGS}/generate.m" ]; then
  echo "corpus generation matlab script '${CGS}/generate.m' missing"
  exit 1
fi

# Clear target directory
[ -d "${COD}" ] && rm -r "${COD}"
mkdir -p "${COD}"

# Default to one block
if [ -z "$PARALLEL_CORPUS" ]; then
  PARALLEL_CORPUS=1
fi

# Generate training and testing data
echo "perform corpus generation in (max) ${PARALLEL_CORPUS} blocks"
mkdir -p "${COD}/train"
mkdir -p "${COD}/test"
if [ $PARALLEL_CORPUS -gt 1 ]; then
  echo "disable verbose ouput because multiple threads will be used"
  VERBOSE=0
else
  VERBOSE=1
fi
for ((I=1;$I<$[${PARALLEL_CORPUS}+1];I++)); do
  (echo "generate('${COD}/train', ${TRAIN_SAMPELS}, ${I}, ${VERBOSE}); generate('${COD}/test', ${TEST_SAMPELS}, $[${PARALLEL_CORPUS}+${I}], ${VERBOSE});" | run-matlab "${CGS}") &
done

wait || exit 1
