#!/bin/bash
#USAGE      corpus-matrix [TRAIN_SAMPELS] [TEST_SAMPELS] [SNRS] [SIL]
#TASK       set up a matrix sentence corpus
#COPYRIGHT  (C) 2014-2018 Marc René Schädler

# Get the directory this script is stored in and its name
DIR=$(cd "$( dirname "$0" )" && pwd)
SCN=$(basename "$0")

# Load configuration file
CGF="${DIR}/${SCN}.cfg"
[ -f "${CGF}" ] && source "${CGF}"

# Load additional scripts from sub-script directory
SSD="${DIR}/${SCN}.d"
[ -d "${SSD}" ] && PATH="${PATH}:${SSD}"

# Get arguments
[ -n "$1" ] && TRAIN_SAMPELS="$1"
[ -n "$2" ] && TEST_SAMPELS="$2"
[ -n "$3" ] && TRAIN_SNRS="$3" && TEST_SNRS="$3"
[ -n "$4" ] && SIL="$4"

if [ $# -gt 0 ]; then
  echo "corpus generation config will be overwritten"
  OVERRIDE=true
else
  OVERRIDE=false
fi

# Working directory is the current directory
WKD="${PWD}"

# Corpus cornfig directory
CCD="${WKD}/config/corpus"

# Training config directory
TCD="${WKD}/config/training"

# Recognition config directory
RCD="${WKD}/config/recognition"

# Evaluation config directory
ECD="${WKD}/config/evaluation"

# Figure scripts directory
FCD="${WKD}/config/figures"

# Copy corpus generation script and format file
echo "update corpus environment '${CCD}'"
mkdir -p "${CCD}"
echo "copy corpus generation script '${CCD}/generate'"
cp "${SSD}/generate" "${CCD}/generate" || exit 1
echo "copy corpus format file '${CCD}/format.cfg'"
cp "${SSD}/format.cfg" "${CCD}/format.cfg" || exit 1

# Write corpus generation config
if [ ! -e "${CCD}/generate.cfg" ] || $OVERRIDE; then
  echo "write corpus generation config file '${CCD}/generate.cfg'"
  echo "# corpus generation config" > "${CCD}/generate.cfg"
  echo "TRAIN_SAMPELS='${TRAIN_SAMPELS}'" >> "${CCD}/generate.cfg"
  echo "TEST_SAMPELS='${TEST_SAMPELS}'" >> "${CCD}/generate.cfg"
  echo "TRAIN_SNRS='${TRAIN_SNRS}'" >> "${CCD}/generate.cfg"
  echo "TEST_SNRS='${TEST_SNRS}'" >> "${CCD}/generate.cfg"
  echo "SIL='${SIL}'" >> "${CCD}/generate.cfg"
fi

# Update environments
echo "update training environment '${TCD}/environment'"
mkdir -p "${TCD}/environment"

echo "update recognition environment '${RCD}/environment'"
mkdir -p "${RCD}/environment"
if [ -e "${SSD}/grammar" ]; then
  echo "copy grammar '${RCD}/environment/grammar'"
  cp -L "${SSD}/grammar" "${RCD}/environment/grammar" || exit 1
fi

echo "update evaluation environment '${ECD}'"
mkdir -p "${ECD}"
if [ -e "${SSD}/evaluate" ]; then
  echo "copy default evaluation script to '${ECD}/evaluate'"
  cp -L "${SSD}/evaluate" "${ECD}/evaluate" || exit 1
fi

echo "update figure environment '${FCD}'"
mkdir -p "${FCD}/matlab"
echo "copy matlab figure scripts to '${FCD}/matlab/'"
cp -L -r "${SSD}/matlab/figures/"* "${FCD}/matlab/" || exit 1
echo "default to '${SCORING}'-scoring"
echo ",'${SCORING}'" > "${FCD}/arguments" || exit 1

# Stop here if only configuring
echo "configuration finished"
$CONFIG && exit 0

# Make directories for source files
mkdir -p "${WKD}/source/speech"
mkdir -p "${WKD}/source/noise"
mkdir -p "${WKD}/source/hrir-speech"
mkdir -p "${WKD}/source/hrir-noise"

echo "${SCN} finished"
