#!/bin/bash
#
# A function that starts the training script
# 
# Author 2014-2021 Marc René Schädler

# Get the directory this script is stored in and its name
DIR=$(cd "$( dirname "$0" )" && pwd)
SCN=$(basename "$0")

# Load configuration file
CGF="${DIR}/${SCN}.cfg"
[ -f "${CGF}" ] && source "${CGF}"

# Load additional scripts from sub-script directory
SSD="${DIR}/${SCN}.d"
[ -d "${SSD}" ] && PATH="${PATH}:${SSD}"

# Get arguments
[ -n "$1" ] && BLOCK="$1"

# Work directory is current directory
WKD="${PWD}"

# Training config directory
TCD="${WKD}/config/training"

# Log directory
LGD="${WKD}/log"

# Check condition list exists
if [ ! -f "${TCD}/conditionlist" ]; then
  echo "missing condition list '${TCD}/conditionlist'"
  exit 1
fi

# Check if there are any conditions
TRAIN_CONDITIONS=($(cat "${TCD}/conditionlist"))
if [ -z "${TRAIN_CONDITIONS}" ]; then
  echo "no training conditions found"
  exit 1
fi

mkdir -p "${LGD}"
LOGFILE="${LGD}/batchtrain-${BLOCK}.log"
[ -e "${LOGFILE}" ] && rm "${LOGFILE}"

for ((I=0;$I<${#TRAIN_CONDITIONS[@]};I++)); do
  CONDITION="${TRAIN_CONDITIONS[$I]}"
  if [ -n "$CONDITION" ]; then
    # Start training
    train "${CONDITION}" &>> "${LOGFILE}" || exit 1
    # Indicate progress
    echo -n "."
  fi
done
