#!/bin/bash

SOURCELIST="$1"
TARGETLIST="$2"
INCREMENT="$3"
OFFSET="$4"
shift 4

IFS=$'\n' read -d '' -r -a SOURCEFILES < "$SOURCELIST"
IFS=$'\n' read -d '' -r -a TARGETFILES < "$TARGETLIST"

PROGRESS='0123456789#'

for ((I=$[${OFFSET}-1];$I<${#SOURCEFILES[@]};I+=${INCREMENT})); do
  cp "${SOURCEFILES[$I]}" "${TARGETFILES[$I]}"
  echo -n "${PROGRESS:$[10*${I}/${#SOURCEFILES[@]}]:1}"
done

