#!/bin/bash
#
# A function that starts the recognition script
#
# Copyright (C) 2014-2016 Marc René Schädler

# Get the directory this script is stored in and its name
DIR=$(cd "$( dirname "$0" )" && pwd)
SCN=$(basename "$0")

# Load configuration file
CGF="${DIR}/${SCN}.cfg"
[ -f "${CGF}" ] && source "${CGF}"

# Load additional scripts from sub-script directory
SSD="${DIR}/${SCN}.d"
[ -d "${SSD}" ] && PATH="${PATH}:${SSD}"

# Get arguments
[ -n "$1" ] && BLOCK="$1"

# Work directory is current directory
WKD="${PWD}"

# Recognition config directory
RCD="${WKD}/config/recognition"

# Log directory
LGD="${WKD}/log"

# Check condition list exists
if [ ! -f "${RCD}/conditionlist" ]; then
  echo "missing condition list '${RCD}/conditionlist'"
  exit 1
fi

# Check if there are any conditions
TEST_CONDITIONS=($(cat "${RCD}/conditionlist"))
if [ -z "${TEST_CONDITIONS}" ]; then
  echo "no testing conditions found"
  exit 1
fi

mkdir -p "${LGD}"
LOGFILE="${LGD}/batchrecog-${BLOCK}.log"
[ -e "${LOGFILE}" ] && rm "${LOGFILE}"

for ((I=0;$I<${#TEST_CONDITIONS[@]};I++)); do
  CONDITION="${TEST_CONDITIONS[$I]}"
  if [ -n "$CONDITION" ]; then
    # Start recognition
    recog "${CONDITION}" &>> "${LOGFILE}" || exit 1
    # Indicate progress
    echo -n "."
  fi
done
